martynsmith/node-irc

README.md
In the issue #254, an user is asking why the main README is showing an use case of the master branch while npm installs the 0.3.x branch. I added a small clarification on the master README explaining the situation.
=> update README regarding npm and the 0.3.x branch

.jscsrc, .travis.yml, example/bot.js, example/secure.js, lib/codes.js, lib/colors.js, lib/irc.js, package.json, test/parse-line.js
Start using [travis-ci](https://travis-ci.org) for CI. Use [jscs](https://github.com/jscs-dev/node-jscs) for lint, and run `npm test` for tests.
CI helps speed up development with automatic validation of incoming Pull Requests. Using a linter makes a consistent code style for readability and catching simple and common bugs.
Using `jscs` this implements *mostly* the [airbnb javascript style](https://github.com/airbnb/javascript). The differences are:
* 4 spaces for indentation instead of 2
* camelCase isn't required for `Object` properties
* `self` is the accepted keyword for storing context across closures instead of `_this`
* Don't require a single `var` statement per scope
=> Add travis with lint and tests

lib/irc.js
When sending a message to IRC, the message is relayed to other
servers and other clients by the server and needs to fit within
the max line length for server messages (512). What this means
is that the actual content of the message needs to be truncated
based on the length of the user's nick, hostname, and the kind
of message being sent (PRIVMSG, NOTICE). The current code,
in addition to hardcoding the wrap length at the absolute
max line length (not taking any of this into consideration),
is rather ugly and hard to follow. I've abstracted the logic
into something easier to follow, correct, and reuseable. It'll
be easy to expand it to ACTION.
TODO: maintain colors and other formatting across wrapped
messages. Textual does this for PRIVMSGs, at least, so we can try
looking there for …
=> Add proper long line wrapping.

README.md, docs/API.rst, lib/irc.js, package.json
For machines with multiple IPs or people who want to use IPv6
=> Add option to specify bind address when connecting

package.json, test/parse-line.js
Also get rid of underscore. 
This is a duplicate of #273 based on `master` instead of `0.3.x`
=> fix(tests): Ditch mocha and should for tape!

lib/codes.js, lib/irc.js
This just removes the // {{{ and // }}} littered throughout the code.
Replaces #272 as this is rebased on `master` instead of `0.3.x`
=> fix(style): Remove folding hints from codes and irc.

lib/irc.js
This is a small change that should be a no-op. It isn't safe to rely one `process.EventEmitter` as this is an underlying implementation detail and is a remnant of an older and scarier time.
=> fix(irc.js): Use the proper EventEmitter class.

lib/irc.js
Webirc is used for multiple users to connect from your node-irc server to irc to get the clients ip.
Get the users ip and hostname and send it like this:
webirc = {"pass":"WebIrcPassWord","host":"my.host.com", "ip":"123.123.12.12"};
http://wiki.mibbit.com/index.php/Enable_Mibbit_on_Your_IRC_Server
How to configure your server for Webirc can also be found in your irc server dokumentation.
=> WEBIRC support

package.json, test/mockircd.js, test/test-irc.js, test/test-parse-line.js
This is by no means a finished product. Just a jumping off point to get a discussion started.
`package.json`: Change the test script so that we only test files in the `test` directory that start with `test-`
`test/mockircd.js`: A simple mock server that allows us to send and receive data, and makes that data retrievable later. This isn't supposed to be an implementation if an ircd, more a tool for unit testing.
`test/test-irc.js`: The beginnings of testing the irc part.
`test/test-parse-message.js`: Renamed so that it would be run by `npm test`. Removed an unneeded jshint line.
=> WIP: fix(tests): A first attempt at a sane pattern to begin testing the handling of the protocol.

lib/irc.js
Also don't send the WEBIRC message if all of the required options aren't defined.
=> fix(webirc): Set sane defaults for WEBIRC options.

lib/irc.js
IRC Protocol use CR-LF, but legacy IRC server send other code.
http://tools.ietf.org/html/rfc1459.html#section-8
So, replace split string from \r\n with /\r\n|\r|\n/
=> Fix data split delimiter

lib/irc.js, lib/parse_message.js, test/test-parse-line.js
This is mostly is a first step to make the message parser less coupled with the main IRC lib.
This is a no-op, cosmetic change.
=> fix(parseMessage): Factor parseMessage to another file for decoupling.

lib/irc.js, test/test-433-before-001.js
... and while here, fix the hostmask calculation. It was using
the length of the message rather than the last part, therefore
wrapping incorrectly and storing the incorrect hostname.
=> Write a test for setting the hostmask when nick is in use

lib/irc.js
* Add a newline between functions where it was missing
* Remove the newline between the `Client` constructor and its inherit
statement
=> fix(style): Clean up various style issues in irc.js

docs/API.rst, lib/irc.js
autorejoin is the cancer that is killing IRC.
=> do not autorejoin on kicks. bad bot! no cookie!

lib/parse_message.js, package.json, test/data/fixtures.json, test/test-parse-line.js
This doesn't touch the formatting stuff, because it's not really
feasible to do that cleanly in an API-compatible way, and I think
that the user is better off doing that in their own code anyway.
This closes #297.
=> Bring in irc-colors for stripping colors

docs/API.rst
I ended up writing an entire module to handle user information in my project and then discovered by accident that all of this information was already provided by Client.chans
:crying_cat_face:
=> Added a bit more information about Client.chans

lib/irc.js, test/test-irc.js
This was left over from fixing the SSL connection issues. Add a
test as well to ensure it works now and to ensure it doesn't
break in future.
=> Fix option handling when passing a secure object

test/helpers.js
Fixes requiring in tests on Windows (and probably other magical systems).
=> Rember to add path.resolve while requiring things!

lib/irc.js, test/data/fixtures.json, test/test-double-crlf.js
I was using this to interact with twitch irc and it kept crashing because the service occasionally sends a double line break at the end of a line, this was an easy fix but I'm not sure it's in the right place. Feel free to refuse it.
=> fix blank lines being passed to parse message

lib/irc.js
This is a simple fix to ensure whois callbacks are fired when a user's name is capitalized differently than the whois response. Currently, a whois callback will never be fired unless the whois nick exactly matches.
For example, if a user "Rachel" is connected to IRC:
```
client.whois("rachel", function() {
// This callback is never fired, because "rachel" != "Rachel"
});
```
This pull request partially solves issue #322
=> Fixed case sensitivity bug in client.whois()

lib/irc.js, package.json, test/data/fixtures.json, test/test-convert-encoding.js
For example string 'Elizabeth' passed through icu-charset-detector returns charset ibm424_rtl and Iconv cannot convert from ibm424_rtl to utf8. Enclosing the charset conversion inside try catch and returning the original buffer if it throws any errors so that it doesn't crash.
=> Fix charset conversion for invalid charsets 

docs/API.rst
Adds a couple of updates to the API documentation - namely adding the `selfMessage` event emitted and the undocumented `Client.nick` internal variable.
=> Update API documentation with missing event and internal variable

.travis.yml
- this way, we first run tests on older node (0.10.x), which is still installed
on majority of computers.
=> Travis: Sort supported node versions

lib/irc.js
Fixed case where event would not be triggered, because case-sensitivity is not checked between 2 variables.
=> Bug fix: 'pm' event wouldnt always be trigged

lib/irc.js
node v0.12.1 --use-strict objects with 
SyntaxError: Octal literals are not allowed in strict mode.
to the two lines affected by this PR.
=> SyntaxError: Octal literals are not allowed in strict mode.

package.json
`ansi-color` is only used for tests, so there's no need to put it into dependencies.
=> Move dependency 'ansi-color' to devDependencies

example/bot.js
This keeps the same behaviour for users but minimises the impact on users in the #blah channel.
=> Remove #blah from the example

lib/irc.js
Currently, node-irc sends PASS before CAP REQ, causing Freenode to think the client isn't doing SASL auth. This PR omits sending PASS if `options.sasl` is `true`. Instead, the client sends `CAP REQ`, which the server should respond, `CAP ACK`, which is then handled correctly by node-irc.
I'm pretty sure this bug was introduced in https://github.com/martynsmith/node-irc/commit/c6d42625
=> Fix SASL auth

lib/irc.js
I found that this library lacks support for this command, which my ZNC bouncer seems to send me a lot.
I have implemented support for it and have tested it by using it within my own project which uses this library.
As a special case I have emitted whois information right away because the end command - rpl_endofwho lacks nick so its impossible to match it with original rpl_whoreply
Let me know what you guys think.
=> Adding support for command rpl_whoreply (352)

lib/parse_message.js
Ran into an issue with the message handler returning the "from" variable (nick) as undefined. Noticed the regex does not allow the tilde characters in nicks.
=> Allow tilde in nicks

lib/cycling_ping_timer.js, lib/irc.js
I've re-added support for ping timeout detection and recovery (relevant tickets: #76, #214, #176, #375). This has been tested by hand, but haven't been able to run it in a real environment (and won't, since my team no longer uses IRC), so beware there may yet be bugs.
I decided to err on the side of too "wordy" of code in order to allow easier testing later on and, hopefully, more readability. Feedback on how the code is structured and what could be done better/differently would be much appreciated.
=> Detect and recover from ping timeouts

README.md
The node-icu-charset-detector library details installation instructions for ICU that I found helpful. Thought maybe others would find it helpful too.
=> Added link to install instructions for ICU

lib/irc.js
Because empty string is equivalent to `false`.
=> User status isn't updated on MODE if he's not VOICE or OP

lib/irc.js, test/data/fixtures.json, test/test-irc.js
At some point this got dropped out of the calculations.
=> Respect opt.messageSplit when calculating message length

package.json
Currently building it without these updates will fail so this will hopefully fix it.
=> Update iconv to 2.2.1 and node-icu-charset-detector to 0.2.0 to fix node 6+ support
